### ISSUE TITLE
breadcrumb styling issue

### ISSUE THREAD

**Issue by kat05** [getgrav/grav-theme-afterburner2#1]
the last arrow should not be showing, please see pic.
![grav_afterburner2_crumbs](https://cloud.githubusercontent.com/assets/5719486/4608031/a3ff87ce-526e-11e4-9b63-9aeb99d97c90.png)

this is not an issue when using the bootstrap theme.

**Comment by flaviocopes** [comment]
Cannot recreate, I believe this was fixed
