### ISSUE TITLE
The reserved indicator "@" cannot start a plain scalar

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-theme-afterburner2#5]
Hi,

Grav: 1.6.25
Admin: 1.9.14
AfterburnerV2: 1.8.0

After a fresh Grav install, the first thing I did was install this theme.
My Yaml Linting gave me the following feedback:

`/user/themes/afterburner2/blueprints/item.yaml | The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 2 (near "@extends:").
/user/themes/afterburner2/blueprints/blog.yaml | The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 2 (near "@extends:").
/user/themes/afterburner2/blueprints/asset/file.yaml | The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 29 (near "@media.*.keys").
/user/themes/afterburner2/blueprints/form.yaml | The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 2 (near "@extends: default").
/user/themes/afterburner2/blueprints/modular/text.yaml | The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 2 (near "@extends: default").
/user/themes/afterburner2/blueprints/modular/showcase.yaml | The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 2 (near "@extends: default").
/user/themes/afterburner2/blueprints/modular/features.yaml | The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 2 (near "@extends: default").`

**Comment by rhukster** [comment]
The YAML parser used to be quite lenient and allowed `@` to be unquoted, but newer versions have become more strict.  we actually fall back to an older version if it experiences an error such as this, so Grav should still work.. Even though listing wise it's not strictly compatible.

Simply change the blueprint to `extends@:` or put it in quotes: `"@extends:"`

The theme probably needs an update to reflect this.
